version: '3'
services:

    php-fpm:
        image: eugenebalaban/laravel-php-fpm-debug
        volumes:
            - ./:/var/www/html:cached
            - ./docker/php.ini:/usr/local/etc/php/php.ini:cached
        links:
            - database
        environment:
            - XDEBUG_CONFIG=remote_host=10.200.10.1
            - PHP_IDE_CONFIG=serverName=laravel

    nginx:
        image: eugenebalaban/laravel-nginx
        links:
            - php-fpm
        volumes:
            - ./public:/var/www/html/public:cached
            - ./storage/nginx-logs:/var/log/nginx:cached
            - ./docker/vhost-stage.conf:/etc/nginx/conf.d/default.conf:cached
        ports:
            - "8070:80"

    database:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=laravel
        ports:
            - "33062:3306"
        volumes:
            - ./storage/mysql-data:/var/lib/mysql:cached